services:
  pitrove:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: piTrove
    restart: always
    network_mode: host
    cap_add:
      - SYS_ADMIN
      - SYS_RAWIO
      - SYS_NICE
    devices:
      - /dev/dri:/dev/dri
      - /dev/input:/dev/input
    security_opt:
      - no-new-privileges:true
    environment:
      - SDL_VIDEO_DRIVER=kmsdrm
      - SDL_VIDEO_KMSDRM_DEVICE=${SDL_VIDEO_KMSDRM_DEVICE:-/dev/dri/card1}
      - SDL_KMSDRM_DEVICE_INDEX=${SDL_KMSDRM_DEVICE_INDEX:-1}
      - XDG_CACHE_HOME=/app/cache
      - MESA_SHADER_CACHE_DIR=/app/cache/mesa_shader_cache
    volumes:
      - /dev:/dev
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - ./cache:/app/cache
      - ./config:/app/config
      - ./logs:/app/logs
      - ./subtitles:/app/subtitles
      - ${MEDIA_DIR:-/mnt/nas}:/app/media
